let data = [
  {
    latitude: 36.13793,
    longitude: 138.441899,
    type: 'country',
    name: 'Japan',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: 'Japan',
    country_code: 'JPN',
    continent: 'Asia',
    label: 'Japan',
  },
  {
    latitude: 35,
    longitude: 105,
    type: 'country',
    name: 'China',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: 'China',
    country_code: 'CHN',
    continent: 'Asia',
    label: 'China',
  },
  {
    latitude: 28.560441,
    longitude: 77.202251,
    type: 'venue',
    name: 'Akvo South Asia Hub Office',
    number: null,
    postal_code: null,
    street: null,
    confidence: 1,
    region: 'Delhi',
    region_code: 'DL',
    county: 'South West',
    locality: 'Delhi',
    administrative_area: null,
    neighbourhood: 'Kidwai Nagar West',
    country: 'India',
    country_code: 'IND',
    continent: 'Asia',
    label: 'Akvo South Asia Hub Office, Delhi, India',
  },
  null,
  {
    latitude: 55.859135,
    longitude: 39.579995,
    type: 'continent',
    name: 'Europe',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: null,
    country_code: null,
    continent: 'Europe',
    label: 'Europe',
  },
  {
    latitude: 55.859135,
    longitude: 39.579995,
    type: 'continent',
    name: 'Europe',
    number: null,
    postal_code: null,
    street: null,
    confidence: 1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: null,
    country_code: null,
    continent: 'Europe',
    label: 'Europe',
  },
  {
    latitude: 52.418788,
    longitude: -1.247349,
    type: 'country',
    name: 'United Kingdom',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: 'United Kingdom',
    country_code: 'GBR',
    continent: 'Europe',
    label: 'United Kingdom',
  },
  {
    latitude: 35.0038,
    longitude: 135.74749,
    type: 'venue',
    name: 'Village Kyoto Modern Japanese Futon',
    number: null,
    postal_code: null,
    street: null,
    confidence: 1,
    region: 'Kyoto Prefecture',
    region_code: 'KY',
    county: 'Kyoto',
    locality: 'Kyoto-shi',
    administrative_area: null,
    neighbourhood: null,
    country: 'Japan',
    country_code: 'JPN',
    continent: 'Asia',
    label: 'Village Kyoto Modern Japanese Futon, Kyoto-shi, KY, Japan',
  },
  {
    latitude: 40.67921,
    longitude: -85.70192,
    type: 'locality',
    name: 'America',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.6,
    region: 'Indiana',
    region_code: 'IN',
    county: 'Wabash County',
    locality: 'America',
    administrative_area: 'Liberty Township',
    neighbourhood: null,
    country: 'United States',
    country_code: 'USA',
    continent: 'North America',
    label: 'America, IN, USA',
  },
  {
    latitude: 28.560441,
    longitude: 77.202251,
    type: 'venue',
    name: 'Akvo South Asia Hub Office',
    number: null,
    postal_code: null,
    street: null,
    confidence: 1,
    region: 'Delhi',
    region_code: 'DL',
    county: 'South West',
    locality: 'Delhi',
    administrative_area: null,
    neighbourhood: 'Kidwai Nagar West',
    country: 'India',
    country_code: 'IND',
    continent: 'Asia',
    label: 'Akvo South Asia Hub Office, Delhi, India',
  },
  {
    latitude: 28.560441,
    longitude: 77.202251,
    type: 'venue',
    name: 'Akvo South Asia Hub Office',
    number: null,
    postal_code: null,
    street: null,
    confidence: 1,
    region: 'Delhi',
    region_code: 'DL',
    county: 'South West',
    locality: 'Delhi',
    administrative_area: null,
    neighbourhood: 'Kidwai Nagar West',
    country: 'India',
    country_code: 'IND',
    continent: 'Asia',
    label: 'Akvo South Asia Hub Office, Delhi, India',
  },
  {
    latitude: 36.13793,
    longitude: 138.441899,
    type: 'country',
    name: 'Japan',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: 'Japan',
    country_code: 'JPN',
    continent: 'Asia',
    label: 'Japan',
  },
  {
    latitude: 35.0038,
    longitude: 135.74749,
    type: 'venue',
    name: 'Village Kyoto Modern Japanese Futon',
    number: null,
    postal_code: null,
    street: null,
    confidence: 1,
    region: 'Kyoto Prefecture',
    region_code: 'KY',
    county: 'Kyoto',
    locality: 'Kyoto-shi',
    administrative_area: null,
    neighbourhood: null,
    country: 'Japan',
    country_code: 'JPN',
    continent: 'Asia',
    label: 'Village Kyoto Modern Japanese Futon, Kyoto-shi, KY, Japan',
  },
  {
    latitude: 40.67921,
    longitude: -85.70192,
    type: 'locality',
    name: 'America',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.6,
    region: 'Indiana',
    region_code: 'IN',
    county: 'Wabash County',
    locality: 'America',
    administrative_area: 'Liberty Township',
    neighbourhood: null,
    country: 'United States',
    country_code: 'USA',
    continent: 'North America',
    label: 'America, IN, USA',
  },
  {
    latitude: 55.859135,
    longitude: 39.579995,
    type: 'continent',
    name: 'Europe',
    number: null,
    postal_code: null,
    street: null,
    confidence: 1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: null,
    country_code: null,
    continent: 'Europe',
    label: 'Europe',
  },
  {
    latitude: 36.13793,
    longitude: 138.441899,
    type: 'country',
    name: 'Japan',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: 'Japan',
    country_code: 'JPN',
    continent: 'Asia',
    label: 'Japan',
  },
  {
    latitude: 40.67921,
    longitude: -85.70192,
    type: 'locality',
    name: 'America',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.6,
    region: 'Indiana',
    region_code: 'IN',
    county: 'Wabash County',
    locality: 'America',
    administrative_area: 'Liberty Township',
    neighbourhood: null,
    country: 'United States',
    country_code: 'USA',
    continent: 'North America',
    label: 'America, IN, USA',
  },
  {
    latitude: 36.13793,
    longitude: 138.441899,
    type: 'country',
    name: 'Japan',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: 'Japan',
    country_code: 'JPN',
    continent: 'Asia',
    label: 'Japan',
  },
  {
    latitude: 35.0038,
    longitude: 135.74749,
    type: 'venue',
    name: 'Village Kyoto Modern Japanese Futon',
    number: null,
    postal_code: null,
    street: null,
    confidence: 1,
    region: 'Kyoto Prefecture',
    region_code: 'KY',
    county: 'Kyoto',
    locality: 'Kyoto-shi',
    administrative_area: null,
    neighbourhood: null,
    country: 'Japan',
    country_code: 'JPN',
    continent: 'Asia',
    label: 'Village Kyoto Modern Japanese Futon, Kyoto-shi, KY, Japan',
  },
  {
    latitude: 36.13793,
    longitude: 138.441899,
    type: 'country',
    name: 'Japan',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: 'Japan',
    country_code: 'JPN',
    continent: 'Asia',
    label: 'Japan',
  },
  {
    latitude: 40.67921,
    longitude: -85.70192,
    type: 'locality',
    name: 'America',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.6,
    region: 'Indiana',
    region_code: 'IN',
    county: 'Wabash County',
    locality: 'America',
    administrative_area: 'Liberty Township',
    neighbourhood: null,
    country: 'United States',
    country_code: 'USA',
    continent: 'North America',
    label: 'America, IN, USA',
  },
  {
    latitude: 36.13793,
    longitude: 138.441899,
    type: 'country',
    name: 'Japan',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.1,
    region: null,
    region_code: null,
    county: null,
    locality: null,
    administrative_area: null,
    neighbourhood: null,
    country: 'Japan',
    country_code: 'JPN',
    continent: 'Asia',
    label: 'Japan',
  },
  {
    latitude: 40.67921,
    longitude: -85.70192,
    type: 'locality',
    name: 'America',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.6,
    region: 'Indiana',
    region_code: 'IN',
    county: 'Wabash County',
    locality: 'America',
    administrative_area: 'Liberty Township',
    neighbourhood: null,
    country: 'United States',
    country_code: 'USA',
    continent: 'North America',
    label: 'America, IN, USA',
  },
  {
    latitude: 40.67921,
    longitude: -85.70192,
    type: 'locality',
    name: 'America',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.6,
    region: 'Indiana',
    region_code: 'IN',
    county: 'Wabash County',
    locality: 'America',
    administrative_area: 'Liberty Township',
    neighbourhood: null,
    country: 'United States',
    country_code: 'USA',
    continent: 'North America',
    label: 'America, IN, USA',
  },
  {
    latitude: 40.67921,
    longitude: -85.70192,
    type: 'locality',
    name: 'America',
    number: null,
    postal_code: null,
    street: null,
    confidence: 0.6,
    region: 'Indiana',
    region_code: 'IN',
    county: 'Wabash County',
    locality: 'America',
    administrative_area: 'Liberty Township',
    neighbourhood: null,
    country: 'United States',
    country_code: 'USA',
    continent: 'North America',
    label: 'America, IN, USA',
  },
];

export default data;
